/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.cosmotech.client.model.AnalysisParameter;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * a Parameter Group for an Analysis
 */
@ApiModel(description = "a Parameter Group for an Analysis")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-12T14:39:58.727919+02:00[Europe/Paris]")
public class AnalysisParameterGroup {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, Object> labels = new HashMap<String, Object>();

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private Integer order;

  public static final String SERIALIZED_NAME_IS_TABLE = "isTable";
  @SerializedName(SERIALIZED_NAME_IS_TABLE)
  private Boolean isTable;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private Map<String, Object> options = null;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private String parentId;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<AnalysisParameter> parameters = new ArrayList<AnalysisParameter>();


  public AnalysisParameterGroup id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * the Parameter Group id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "the Parameter Group id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public AnalysisParameterGroup labels(Map<String, Object> labels) {
    
    this.labels = labels;
    return this;
  }

  public AnalysisParameterGroup putLabelsItem(String key, Object labelsItem) {
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * a translated label with key as ISO 639-1 code
   * @return labels
  **/
  @ApiModelProperty(required = true, value = "a translated label with key as ISO 639-1 code")

  public Map<String, Object> getLabels() {
    return labels;
  }


  public void setLabels(Map<String, Object> labels) {
    this.labels = labels;
  }


  public AnalysisParameterGroup order(Integer order) {
    
    this.order = order;
    return this;
  }

   /**
   * the Parameter Group order
   * @return order
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the Parameter Group order")

  public Integer getOrder() {
    return order;
  }


  public void setOrder(Integer order) {
    this.order = order;
  }


  public AnalysisParameterGroup isTable(Boolean isTable) {
    
    this.isTable = isTable;
    return this;
  }

   /**
   * does the group define a table
   * @return isTable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "does the group define a table")

  public Boolean getIsTable() {
    return isTable;
  }


  public void setIsTable(Boolean isTable) {
    this.isTable = isTable;
  }


  public AnalysisParameterGroup options(Map<String, Object> options) {
    
    this.options = options;
    return this;
  }

  public AnalysisParameterGroup putOptionsItem(String key, Object optionsItem) {
    if (this.options == null) {
      this.options = new HashMap<String, Object>();
    }
    this.options.put(key, optionsItem);
    return this;
  }

   /**
   * freeform options
   * @return options
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "freeform options")

  public Map<String, Object> getOptions() {
    return options;
  }


  public void setOptions(Map<String, Object> options) {
    this.options = options;
  }


  public AnalysisParameterGroup parentId(String parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * the Simulator Analysis Group parent Id
   * @return parentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the Simulator Analysis Group parent Id")

  public String getParentId() {
    return parentId;
  }


  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  public AnalysisParameterGroup parameters(List<AnalysisParameter> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public AnalysisParameterGroup addParametersItem(AnalysisParameter parametersItem) {
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * a list of Simulator Analysis Parameters
   * @return parameters
  **/
  @ApiModelProperty(required = true, value = "a list of Simulator Analysis Parameters")

  public List<AnalysisParameter> getParameters() {
    return parameters;
  }


  public void setParameters(List<AnalysisParameter> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisParameterGroup analysisParameterGroup = (AnalysisParameterGroup) o;
    return Objects.equals(this.id, analysisParameterGroup.id) &&
        Objects.equals(this.labels, analysisParameterGroup.labels) &&
        Objects.equals(this.order, analysisParameterGroup.order) &&
        Objects.equals(this.isTable, analysisParameterGroup.isTable) &&
        Objects.equals(this.options, analysisParameterGroup.options) &&
        Objects.equals(this.parentId, analysisParameterGroup.parentId) &&
        Objects.equals(this.parameters, analysisParameterGroup.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, labels, order, isTable, options, parentId, parameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisParameterGroup {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    isTable: ").append(toIndentedString(isTable)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

