/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.8-SNAPSHOT
 * Contact: platform@cosmotech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * the value of a Solution Run Template parameter for a Scenario
 */
@ApiModel(description = "the value of a Solution Run Template parameter for a Scenario")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-19T13:52:41.001262020Z[Etc/UTC]")
public class ScenarioRunTemplateParameterValue {
  public static final String SERIALIZED_NAME_PARAMETER_ID = "parameterId";
  @SerializedName(SERIALIZED_NAME_PARAMETER_ID)
  private String parameterId;

  public static final String SERIALIZED_NAME_VAR_TYPE = "varType";
  @SerializedName(SERIALIZED_NAME_VAR_TYPE)
  private String varType;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_IS_INHERITED = "isInherited";
  @SerializedName(SERIALIZED_NAME_IS_INHERITED)
  private Boolean isInherited;


  public ScenarioRunTemplateParameterValue parameterId(String parameterId) {
    
    this.parameterId = parameterId;
    return this;
  }

   /**
   * the parameter Id
   * @return parameterId
  **/
  @ApiModelProperty(required = true, value = "the parameter Id")

  public String getParameterId() {
    return parameterId;
  }


  public void setParameterId(String parameterId) {
    this.parameterId = parameterId;
  }


   /**
   * the parameter value type
   * @return varType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the parameter value type")

  public String getVarType() {
    return varType;
  }




  public ScenarioRunTemplateParameterValue value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * the parameter value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "the parameter value")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public ScenarioRunTemplateParameterValue isInherited(Boolean isInherited) {
    
    this.isInherited = isInherited;
    return this;
  }

   /**
   * whether or not the value is inherited from parent or has been changed
   * @return isInherited
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "whether or not the value is inherited from parent or has been changed")

  public Boolean getIsInherited() {
    return isInherited;
  }


  public void setIsInherited(Boolean isInherited) {
    this.isInherited = isInherited;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScenarioRunTemplateParameterValue scenarioRunTemplateParameterValue = (ScenarioRunTemplateParameterValue) o;
    return Objects.equals(this.parameterId, scenarioRunTemplateParameterValue.parameterId) &&
        Objects.equals(this.varType, scenarioRunTemplateParameterValue.varType) &&
        Objects.equals(this.value, scenarioRunTemplateParameterValue.value) &&
        Objects.equals(this.isInherited, scenarioRunTemplateParameterValue.isInherited);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameterId, varType, value, isInherited);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScenarioRunTemplateParameterValue {\n");
    sb.append("    parameterId: ").append(toIndentedString(parameterId)).append("\n");
    sb.append("    varType: ").append(toIndentedString(varType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    isInherited: ").append(toIndentedString(isInherited)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

