/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * details information on Workspace User
 */
@ApiModel(description = "details information on Workspace User")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-15T18:07:38.724376+02:00[Europe/Paris]")
public class WorkspaceUserDetailsAllOf {
  public static final String SERIALIZED_NAME_ORGANIZATION_ID = "organizationId";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ID)
  private String organizationId;

  public static final String SERIALIZED_NAME_ORGANIZATION_ROLES = "organizationRoles";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ROLES)
  private List<String> organizationRoles = null;

  public static final String SERIALIZED_NAME_WORKSPACE_ID = "workspaceId";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_ID)
  private String workspaceId;


   /**
   * the Organization Id context
   * @return organizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the Organization Id context")

  public String getOrganizationId() {
    return organizationId;
  }




   /**
   * the Organizations roles for the User
   * @return organizationRoles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the Organizations roles for the User")

  public List<String> getOrganizationRoles() {
    return organizationRoles;
  }




   /**
   * the Workspace Id context
   * @return workspaceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "the Workspace Id context")

  public String getWorkspaceId() {
    return workspaceId;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceUserDetailsAllOf workspaceUserDetailsAllOf = (WorkspaceUserDetailsAllOf) o;
    return Objects.equals(this.organizationId, workspaceUserDetailsAllOf.organizationId) &&
        Objects.equals(this.organizationRoles, workspaceUserDetailsAllOf.organizationRoles) &&
        Objects.equals(this.workspaceId, workspaceUserDetailsAllOf.workspaceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationId, organizationRoles, workspaceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceUserDetailsAllOf {\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    organizationRoles: ").append(toIndentedString(organizationRoles)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

