/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.api;

import com.cosmotech.client.ApiCallback;
import com.cosmotech.client.ApiClient;
import com.cosmotech.client.ApiException;
import com.cosmotech.client.ApiResponse;
import com.cosmotech.client.Configuration;
import com.cosmotech.client.Pair;
import com.cosmotech.client.ProgressRequestBody;
import com.cosmotech.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;
import com.cosmotech.client.model.Simulator;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SimulatorApi {
    private ApiClient localVarApiClient;

    public SimulatorApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SimulatorApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for createSimulator
     * @param organizationId the Organization identifier (required)
     * @param simulator the Simulator to create (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createSimulatorCall(String organizationId, Simulator simulator, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = simulator;

        // create path and map variables
        String localVarPath = "/organizations/{organization_id}/simulators"
            .replaceAll("\\{" + "organization_id" + "\\}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oAuth2AuthCode" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createSimulatorValidateBeforeCall(String organizationId, Simulator simulator, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling createSimulator(Async)");
        }
        
        // verify the required parameter 'simulator' is set
        if (simulator == null) {
            throw new ApiException("Missing the required parameter 'simulator' when calling createSimulator(Async)");
        }
        

        okhttp3.Call localVarCall = createSimulatorCall(organizationId, simulator, _callback);
        return localVarCall;

    }

    /**
     * Register a new simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulator the Simulator to create (required)
     * @return Simulator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public Simulator createSimulator(String organizationId, Simulator simulator) throws ApiException {
        ApiResponse<Simulator> localVarResp = createSimulatorWithHttpInfo(organizationId, simulator);
        return localVarResp.getData();
    }

    /**
     * Register a new simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulator the Simulator to create (required)
     * @return ApiResponse&lt;Simulator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Simulator> createSimulatorWithHttpInfo(String organizationId, Simulator simulator) throws ApiException {
        okhttp3.Call localVarCall = createSimulatorValidateBeforeCall(organizationId, simulator, null);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Register a new simulator (asynchronously)
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulator the Simulator to create (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createSimulatorAsync(String organizationId, Simulator simulator, final ApiCallback<Simulator> _callback) throws ApiException {

        okhttp3.Call localVarCall = createSimulatorValidateBeforeCall(organizationId, simulator, _callback);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteSimulator
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSimulatorCall(String organizationId, String simulatorId, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{organization_id}/simulators/{simulator_id}"
            .replaceAll("\\{" + "organization_id" + "\\}", localVarApiClient.escapeString(organizationId.toString()))
            .replaceAll("\\{" + "simulator_id" + "\\}", localVarApiClient.escapeString(simulatorId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oAuth2AuthCode" };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteSimulatorValidateBeforeCall(String organizationId, String simulatorId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling deleteSimulator(Async)");
        }
        
        // verify the required parameter 'simulatorId' is set
        if (simulatorId == null) {
            throw new ApiException("Missing the required parameter 'simulatorId' when calling deleteSimulator(Async)");
        }
        

        okhttp3.Call localVarCall = deleteSimulatorCall(organizationId, simulatorId, _callback);
        return localVarCall;

    }

    /**
     * Delete a simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @return Simulator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public Simulator deleteSimulator(String organizationId, String simulatorId) throws ApiException {
        ApiResponse<Simulator> localVarResp = deleteSimulatorWithHttpInfo(organizationId, simulatorId);
        return localVarResp.getData();
    }

    /**
     * Delete a simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @return ApiResponse&lt;Simulator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Simulator> deleteSimulatorWithHttpInfo(String organizationId, String simulatorId) throws ApiException {
        okhttp3.Call localVarCall = deleteSimulatorValidateBeforeCall(organizationId, simulatorId, null);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a simulator (asynchronously)
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSimulatorAsync(String organizationId, String simulatorId, final ApiCallback<Simulator> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteSimulatorValidateBeforeCall(organizationId, simulatorId, _callback);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findAllSimulators
     * @param organizationId the Organization identifier (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAllSimulatorsCall(String organizationId, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{organization_id}/simulators"
            .replaceAll("\\{" + "organization_id" + "\\}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oAuth2AuthCode" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findAllSimulatorsValidateBeforeCall(String organizationId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling findAllSimulators(Async)");
        }
        

        okhttp3.Call localVarCall = findAllSimulatorsCall(organizationId, _callback);
        return localVarCall;

    }

    /**
     * List all Simulators
     * 
     * @param organizationId the Organization identifier (required)
     * @return List&lt;Simulator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
     </table>
     */
    public List<Simulator> findAllSimulators(String organizationId) throws ApiException {
        ApiResponse<List<Simulator>> localVarResp = findAllSimulatorsWithHttpInfo(organizationId);
        return localVarResp.getData();
    }

    /**
     * List all Simulators
     * 
     * @param organizationId the Organization identifier (required)
     * @return ApiResponse&lt;List&lt;Simulator&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Simulator>> findAllSimulatorsWithHttpInfo(String organizationId) throws ApiException {
        okhttp3.Call localVarCall = findAllSimulatorsValidateBeforeCall(organizationId, null);
        Type localVarReturnType = new TypeToken<List<Simulator>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List all Simulators (asynchronously)
     * 
     * @param organizationId the Organization identifier (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findAllSimulatorsAsync(String organizationId, final ApiCallback<List<Simulator>> _callback) throws ApiException {

        okhttp3.Call localVarCall = findAllSimulatorsValidateBeforeCall(organizationId, _callback);
        Type localVarReturnType = new TypeToken<List<Simulator>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findSimulatorById
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the Simulator details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findSimulatorByIdCall(String organizationId, String simulatorId, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{organization_id}/simulators/{simulator_id}"
            .replaceAll("\\{" + "organization_id" + "\\}", localVarApiClient.escapeString(organizationId.toString()))
            .replaceAll("\\{" + "simulator_id" + "\\}", localVarApiClient.escapeString(simulatorId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oAuth2AuthCode" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findSimulatorByIdValidateBeforeCall(String organizationId, String simulatorId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling findSimulatorById(Async)");
        }
        
        // verify the required parameter 'simulatorId' is set
        if (simulatorId == null) {
            throw new ApiException("Missing the required parameter 'simulatorId' when calling findSimulatorById(Async)");
        }
        

        okhttp3.Call localVarCall = findSimulatorByIdCall(organizationId, simulatorId, _callback);
        return localVarCall;

    }

    /**
     * Get the details of a simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @return Simulator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the Simulator details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public Simulator findSimulatorById(String organizationId, String simulatorId) throws ApiException {
        ApiResponse<Simulator> localVarResp = findSimulatorByIdWithHttpInfo(organizationId, simulatorId);
        return localVarResp.getData();
    }

    /**
     * Get the details of a simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @return ApiResponse&lt;Simulator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the Simulator details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Simulator> findSimulatorByIdWithHttpInfo(String organizationId, String simulatorId) throws ApiException {
        okhttp3.Call localVarCall = findSimulatorByIdValidateBeforeCall(organizationId, simulatorId, null);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get the details of a simulator (asynchronously)
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the Simulator details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findSimulatorByIdAsync(String organizationId, String simulatorId, final ApiCallback<Simulator> _callback) throws ApiException {

        okhttp3.Call localVarCall = findSimulatorByIdValidateBeforeCall(organizationId, simulatorId, _callback);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateSimulator
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param simulator the new Simulator details. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateSimulatorCall(String organizationId, String simulatorId, Simulator simulator, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = simulator;

        // create path and map variables
        String localVarPath = "/organizations/{organization_id}/simulators/{simulator_id}"
            .replaceAll("\\{" + "organization_id" + "\\}", localVarApiClient.escapeString(organizationId.toString()))
            .replaceAll("\\{" + "simulator_id" + "\\}", localVarApiClient.escapeString(simulatorId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oAuth2AuthCode" };
        return localVarApiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateSimulatorValidateBeforeCall(String organizationId, String simulatorId, Simulator simulator, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling updateSimulator(Async)");
        }
        
        // verify the required parameter 'simulatorId' is set
        if (simulatorId == null) {
            throw new ApiException("Missing the required parameter 'simulatorId' when calling updateSimulator(Async)");
        }
        
        // verify the required parameter 'simulator' is set
        if (simulator == null) {
            throw new ApiException("Missing the required parameter 'simulator' when calling updateSimulator(Async)");
        }
        

        okhttp3.Call localVarCall = updateSimulatorCall(organizationId, simulatorId, simulator, _callback);
        return localVarCall;

    }

    /**
     * Update a simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param simulator the new Simulator details. (required)
     * @return Simulator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public Simulator updateSimulator(String organizationId, String simulatorId, Simulator simulator) throws ApiException {
        ApiResponse<Simulator> localVarResp = updateSimulatorWithHttpInfo(organizationId, simulatorId, simulator);
        return localVarResp.getData();
    }

    /**
     * Update a simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param simulator the new Simulator details. (required)
     * @return ApiResponse&lt;Simulator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Simulator> updateSimulatorWithHttpInfo(String organizationId, String simulatorId, Simulator simulator) throws ApiException {
        okhttp3.Call localVarCall = updateSimulatorValidateBeforeCall(organizationId, simulatorId, simulator, null);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a simulator (asynchronously)
     * 
     * @param organizationId the Organization identifier (required)
     * @param simulatorId the Simulator identifier (required)
     * @param simulator the new Simulator details. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> the Simulator specified is unknown or you don&#39;t have access to it </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateSimulatorAsync(String organizationId, String simulatorId, Simulator simulator, final ApiCallback<Simulator> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateSimulatorValidateBeforeCall(organizationId, simulatorId, simulator, _callback);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for upload
     * @param organizationId the Organization identifier (required)
     * @param body the Simulator to upload and register (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadCall(String organizationId, File body, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/organizations/{organization_id}/simulators/upload"
            .replaceAll("\\{" + "organization_id" + "\\}", localVarApiClient.escapeString(organizationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/yaml"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oAuth2AuthCode" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadValidateBeforeCall(String organizationId, File body, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organizationId' is set
        if (organizationId == null) {
            throw new ApiException("Missing the required parameter 'organizationId' when calling upload(Async)");
        }
        
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling upload(Async)");
        }
        

        okhttp3.Call localVarCall = uploadCall(organizationId, body, _callback);
        return localVarCall;

    }

    /**
     * Upload and register a new simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param body the Simulator to upload and register (required)
     * @return Simulator
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public Simulator upload(String organizationId, File body) throws ApiException {
        ApiResponse<Simulator> localVarResp = uploadWithHttpInfo(organizationId, body);
        return localVarResp.getData();
    }

    /**
     * Upload and register a new simulator
     * 
     * @param organizationId the Organization identifier (required)
     * @param body the Simulator to upload and register (required)
     * @return ApiResponse&lt;Simulator&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Simulator> uploadWithHttpInfo(String organizationId, File body) throws ApiException {
        okhttp3.Call localVarCall = uploadValidateBeforeCall(organizationId, body, null);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Upload and register a new simulator (asynchronously)
     * 
     * @param organizationId the Organization identifier (required)
     * @param body the Simulator to upload and register (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> the simulator details </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadAsync(String organizationId, File body, final ApiCallback<Simulator> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadValidateBeforeCall(organizationId, body, _callback);
        Type localVarReturnType = new TypeToken<Simulator>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
