/*
 * Cosmo Tech Platform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 2.3.12-SNAPSHOT
 * Contact: platform@cosmotech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScenarioRunTemplateParameterValue
 */
public class ScenarioRunTemplateParameterValueTest {
    private final ScenarioRunTemplateParameterValue model = new ScenarioRunTemplateParameterValue();

    /**
     * Model tests for ScenarioRunTemplateParameterValue
     */
    @Test
    public void testScenarioRunTemplateParameterValue() {
        // TODO: test ScenarioRunTemplateParameterValue
    }

    /**
     * Test the property 'parameterId'
     */
    @Test
    public void parameterIdTest() {
        // TODO: test parameterId
    }

    /**
     * Test the property 'varType'
     */
    @Test
    public void varTypeTest() {
        // TODO: test varType
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'isInherited'
     */
    @Test
    public void isInheritedTest() {
        // TODO: test isInherited
    }

}
