/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import com.cosmotech.client.model.RunTemplateParameterValue;
import com.cosmotech.client.model.ScenarioRunContainers;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScenarioRunAllOf
 */
public class ScenarioRunAllOfTest {
    private final ScenarioRunAllOf model = new ScenarioRunAllOf();

    /**
     * Model tests for ScenarioRunAllOf
     */
    @Test
    public void testScenarioRunAllOf() {
        // TODO: test ScenarioRunAllOf
    }

    /**
     * Test the property 'datasetList'
     */
    @Test
    public void datasetListTest() {
        // TODO: test datasetList
    }

    /**
     * Test the property 'parametersValues'
     */
    @Test
    public void parametersValuesTest() {
        // TODO: test parametersValues
    }

    /**
     * Test the property 'sendInputToDataWarehouse'
     */
    @Test
    public void sendInputToDataWarehouseTest() {
        // TODO: test sendInputToDataWarehouse
    }

    /**
     * Test the property 'dataWarehouseDB'
     */
    @Test
    public void dataWarehouseDBTest() {
        // TODO: test dataWarehouseDB
    }

    /**
     * Test the property 'resultsEventBusResourceUri'
     */
    @Test
    public void resultsEventBusResourceUriTest() {
        // TODO: test resultsEventBusResourceUri
    }

    /**
     * Test the property 'scenariorunEventBusResourceUri'
     */
    @Test
    public void scenariorunEventBusResourceUriTest() {
        // TODO: test scenariorunEventBusResourceUri
    }

    /**
     * Test the property 'nodeLabel'
     */
    @Test
    public void nodeLabelTest() {
        // TODO: test nodeLabel
    }

    /**
     * Test the property 'initContainers'
     */
    @Test
    public void initContainersTest() {
        // TODO: test initContainers
    }

    /**
     * Test the property 'mainContainer'
     */
    @Test
    public void mainContainerTest() {
        // TODO: test mainContainer
    }

}
