/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import com.cosmotech.client.model.SimulationAllOf;
import com.cosmotech.client.model.SimulationAnalysisParameterValue;
import com.cosmotech.client.model.SimulationBase;
import com.cosmotech.client.model.SimulationContainers;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Simulation
 */
public class SimulationTest {
    private final Simulation model = new Simulation();

    /**
     * Model tests for Simulation
     */
    @Test
    public void testSimulation() {
        // TODO: test Simulation
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'workspaceId'
     */
    @Test
    public void workspaceIdTest() {
        // TODO: test workspaceId
    }

    /**
     * Test the property 'workspaceName'
     */
    @Test
    public void workspaceNameTest() {
        // TODO: test workspaceName
    }

    /**
     * Test the property 'scenarioId'
     */
    @Test
    public void scenarioIdTest() {
        // TODO: test scenarioId
    }

    /**
     * Test the property 'scenarioName'
     */
    @Test
    public void scenarioNameTest() {
        // TODO: test scenarioName
    }

    /**
     * Test the property 'simulatorId'
     */
    @Test
    public void simulatorIdTest() {
        // TODO: test simulatorId
    }

    /**
     * Test the property 'simulatorName'
     */
    @Test
    public void simulatorNameTest() {
        // TODO: test simulatorName
    }

    /**
     * Test the property 'simulatorVersion'
     */
    @Test
    public void simulatorVersionTest() {
        // TODO: test simulatorVersion
    }

    /**
     * Test the property 'simulatorAnalysisId'
     */
    @Test
    public void simulatorAnalysisIdTest() {
        // TODO: test simulatorAnalysisId
    }

    /**
     * Test the property 'simulatorAnalysisName'
     */
    @Test
    public void simulatorAnalysisNameTest() {
        // TODO: test simulatorAnalysisName
    }

    /**
     * Test the property 'computeSize'
     */
    @Test
    public void computeSizeTest() {
        // TODO: test computeSize
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'datasetList'
     */
    @Test
    public void datasetListTest() {
        // TODO: test datasetList
    }

    /**
     * Test the property 'parametersValues'
     */
    @Test
    public void parametersValuesTest() {
        // TODO: test parametersValues
    }

    /**
     * Test the property 'sendInputToDataWarehouse'
     */
    @Test
    public void sendInputToDataWarehouseTest() {
        // TODO: test sendInputToDataWarehouse
    }

    /**
     * Test the property 'dataWarehouseDB'
     */
    @Test
    public void dataWarehouseDBTest() {
        // TODO: test dataWarehouseDB
    }

    /**
     * Test the property 'resultsEventBusResourceUri'
     */
    @Test
    public void resultsEventBusResourceUriTest() {
        // TODO: test resultsEventBusResourceUri
    }

    /**
     * Test the property 'simulationEventBusResourceUri'
     */
    @Test
    public void simulationEventBusResourceUriTest() {
        // TODO: test simulationEventBusResourceUri
    }

    /**
     * Test the property 'nodeLabel'
     */
    @Test
    public void nodeLabelTest() {
        // TODO: test nodeLabel
    }

    /**
     * Test the property 'initContainers'
     */
    @Test
    public void initContainersTest() {
        // TODO: test initContainers
    }

    /**
     * Test the property 'mainContainer'
     */
    @Test
    public void mainContainerTest() {
        // TODO: test mainContainer
    }

}
