/*
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import com.cosmotech.client.model.SimulationContainerLogs;
import com.cosmotech.client.model.SimulationLogsOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SimulationLogs
 */
public class SimulationLogsTest {
    private final SimulationLogs model = new SimulationLogs();

    /**
     * Model tests for SimulationLogs
     */
    @Test
    public void testSimulationLogs() {
        // TODO: test SimulationLogs
    }

    /**
     * Test the property 'simulationId'
     */
    @Test
    public void simulationIdTest() {
        // TODO: test simulationId
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'initLogs'
     */
    @Test
    public void initLogsTest() {
        // TODO: test initLogs
    }

    /**
     * Test the property 'mainLogs'
     */
    @Test
    public void mainLogsTest() {
        // TODO: test mainLogs
    }

}
