/*
 * Cosmo Tech Platform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 3.1.3
 * Contact: platform@cosmotech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cosmotech.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkspaceSecret
 */
public class WorkspaceSecretTest {
    private final WorkspaceSecret model = new WorkspaceSecret();

    /**
     * Model tests for WorkspaceSecret
     */
    @Test
    public void testWorkspaceSecret() {
        // TODO: test WorkspaceSecret
    }

    /**
     * Test the property 'dedicatedEventHubKey'
     */
    @Test
    public void dedicatedEventHubKeyTest() {
        // TODO: test dedicatedEventHubKey
    }

}
